USE burgers_db;
CREATE TABLE burgers(
id int(10) NOT NULL AUTO_INCREMENT,
burger_name  VARCHAR(250) NOT NULL,
devoured BOOLEAN DEFAULT false,
date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);